# Generated by Django 4.2.5 on 2024-02-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_posts_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
    ]
