# Generated by Django 4.2.5 on 2024-02-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_posts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mega_info',
            name='map',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='rel_posts',
            field=models.ManyToManyField(to='main.related_posts'),
        ),
    ]
